
name: Maven Verify

on:
  - push
  - pull_request


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Test with Maven
        run: mvn -B test --file pom.xml

      - name: Set up JDK 11 for Sonar # SonarCloud does not support Java 8 anymore!
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: SonarCloud Scan
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
